services:
  client:
    build: ./client
    cap_add: ["NET_ADMIN"]
    sysctls:
      net.ipv4.tcp_syncookies: "0"
    networks:
      client_net:
        ipv4_address: 172.28.1.10
    command: >
      sh -c "
        ip route del default || true;
        ip route add 172.28.2.0/24 via 172.28.1.254;
        ip route add default via 172.28.1.254;
        tail -f /dev/null
      "

  observer:
    image: alpine:latest
    cap_add: ["NET_ADMIN"]
    sysctls:
      net.ipv4.tcp_syncookies: "0"
    networks:
      dmz_net:
        ipv4_address: 172.28.2.30
    command: >
      sh -c "
        apk add --no-cache iputils curl;
        sleep infinity
      "
    # command: >
    #   sh -c "
    #     apk add --no-cache iputils curl;
    #     ip route del default || true;
    #     ip route add 172.28.2.0/24 via 172.28.1.254;
    #     sleep infinity
    #   "

  firewall:
    build: ./firewall
    privileged: true
    cap_add: ["NET_ADMIN", "NET_RAW"]
    sysctls:
      net.ipv4.ip_forward: "1"
      net.ipv4.conf.all.rp_filter: "0"
      net.ipv4.tcp_syncookies: "0"
    environment:
      - TZ=Europe/Stockholm
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      client_net:
        ipv4_address: 172.28.1.254
      dmz_net:
        ipv4_address: 172.28.2.254
    ports:
      - "8080:8080"

  server:
    build: ./server
    cap_add: ["NET_ADMIN"]
    sysctls:
      net.ipv4.tcp_max_syn_backlog: "1"
      net.ipv4.tcp_syn_retries: "1"
      net.ipv4.tcp_synack_retries: "1"
      net.ipv4.tcp_syncookies: "0"
      net.core.somaxconn: "1"
      net.ipv4.tcp_fin_timeout: "5"
      net.ipv4.tcp_keepalive_time: "10"
      net.ipv4.tcp_keepalive_intvl: "5"
      net.ipv4.tcp_orphan_retries: "1"
      net.ipv4.tcp_retries1: "1"
      net.ipv4.tcp_retries2: "2"
    networks:
      dmz_net:
        ipv4_address: 172.28.2.20

networks:
  client_net:
    driver: bridge
    ipam:
      config: [{ subnet: 172.28.1.0/24 }]
  dmz_net:
    driver: bridge
    ipam:
      config: [{ subnet: 172.28.2.0/24 }]
